### PR TITLE
Fix to show ammo

### PR DESCRIPTION
**Pull request by Piotr3k1447**
Fixed show ammo value when there is more than one bow

### CODE REVIEW

**Review by nxPublic — APPROVED** [review]

**Comment by baconparticles** [comment]
Nice catch! :) I didn't imagine someone having multiple bows in their hotkey bar.

**Comment by Piotr3k1447** [comment]
You're welcome

**Comment by Piotr3k1447** [comment]
> You're welcome

If you can make se equip asweel. Thanks

**Comment by baconparticles** [comment]
What does "se equip asweel" mean? Feel free to DM me in the discord.

**Pull request merged**
