### PR TITLE
ValheimPlus Manager for Windows (game/server clients)

### PR DESCRIPTION
**Pull request by rr222cy**
Hi!
I've been working on a manager for ValheimPlus for the last couple of days for easier installation, updating, configuration management and much more. Se the excerpt from the README.md below:

## Features
- Automatically install ValheimPlus to your game client or server client directory
- Manage the configuration of ValheimPlus through a GUI
- Update ValheimPlus directly through ValheimPlus Manager
- Keep settings from previous versions and just add/activate new settings automagically
- Enable/disable ValheimPlus on game client, so you can join non-modded servers on the fly
- Launch Valheim(Plus) from the Manager
- In-app settings of installation paths (ToDo: server paths)
- (Coming) Server list manager, join servers from the Manager
- (Coming) backup your configuration files
- (Coming) backup your game client and server client data
- (Coming) management of server admins
- (Coming) uninstall ValheimPlus from game client/server client
## Requirements
.NET 5 available for download at: https://dotnet.microsoft.com/download/dotnet/5.0/runtime

The application is built to be lightweight and portable, no installation needed since it's a self-contained .exe weighing in at around 15MB.

Would love to see this added to the repository to make management of ValheimPlus easier for the gamers out there, even as tech-savvy it's nice being able to manage updates and configuration through a GUI.

More features coming, this is a first alpha release for receiving feedback.

### CODE REVIEW

**Comment by radmint** [comment]
I pulled this down to check it out and was able to set my valheim installation. The installation said I was on version 0.8.5 but I'm on 0.9.0. When I tried to choose to update, I got an uncaught exception:
```
   at ValheimPlusManager.MainWindow.installClientUpdateButton_Click(Object sender, RoutedEventArgs e) in C:\Users\pdbys\source\repos\manager\ValheimPlus\ValheimPlusManager\ValheimPlusManagerWPF\MainWindow.xaml.cs:line 187
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at ValheimPlusManager.App.Main()
   ```

**Comment by ouvoun** [comment]
This is some neat work!

Do you imagine it could work in concert with r2modman perhaps, though? It would be unfortunate if multiple utilities were needed to install a couple of mods.

**Comment by rr222cy** [comment]
Hi @radmint and @ouvoun !

Radmint first: Correct, the version on the first-time usage is not correct (described this in the readme), this is because there seems to be no reliable way to check which version is installed of ValheimPlus. That is, up until 0.9.2 when you added the version to the config file, thanks! So this bug can now be solved.

Regarding the error it could be a number of things that since this pull request has been resolved, see https://github.com/rr222cy/ValheimPlus-Manager for the latest version of this tool

Next up ouvoun: Thank you very much! I'm uncertain, never used r2modman and after a quick glance at the project it seems to be Electron based, whereas this is a native Windows application. Also as can be seen from the linked repository above the scope of the Manager is a bit wider than just installing/updating the mod.

Thanks for checking it out!

**Comment by radmint** [comment]
@rr222cy would you say that this PR represents completed work? I would like to ask that we only have Pull Requests that would be ready to be merged after a review. If we try to test or review and it's not completed, it's hard to know if an issue we find is resulting from something that's incomplete or if it's a valid issue.

**Comment by radmint** [comment]
Closing after receiving no response

**Pull request closed without merging**
