### PR TITLE
add unix start scripts, add LGSM instructions to README

### PR DESCRIPTION
**Pull request by sirskunkalot**
I've made the unix start scripts more user friendly in terms of comments/config possibilities and added LGSM support to them and instructions for that in the README

### CODE REVIEW

**Comment by sirskunkalot** [comment]
@zedle as requested :)

**Comment by zedle** [comment]
@sirskunkalot Looks good, can you just explain the param passthru in the modified shell script(s) in the README since that's a difference from our current distrib?

**Comment by sirskunkalot** [comment]
@zedle like so?

**Review by zedle — DISMISSED** [review]
lgtm

**Comment by zedle** [comment]
@nxPublic when you're around i think this is a solid improvement to the unix scripts.

**Comment by sirskunkalot** [comment]
I've added another commit right now, describing the client installation for unix, too. So no biggie, if you missed it. No breaking changes this time :)

**Comment by sirskunkalot** [comment]
@zedle @nxPublic did some more FAQ work. advise to merge to keep the questions away ;)

**Comment by nxPublic** [comment]
This needs to be updated for todays new Valheim server update with the new startup commands.

**Comment by sirskunkalot** [comment]
@nxPublic done and testes on my own server

**Review by nxPublic — APPROVED** [review]

**Pull request merged**
