### PR TITLE
Level with stamina usage

### PR DESCRIPTION
**Pull request by ahnguyen09**
It would nice to have the current level show with the experience gain notification. This helps you check your current skill level quickly.
image

### CODE REVIEW

**Review by nxPublic — CHANGES_REQUESTED** [review]
Please resubmit your PR without the project file changes and dependency changes.

It would also be nice to make it a config option.

I like this a lot though!

**Comment by ahnguyen09** [comment]
@nxPublic I did not make it clear but this is an enhancement to the HUD "experienceGainedNotifications" option. Do you still think that it is worth adding another option to display level with the gains? Or we can just include it when experienceGainedNotifications is set to true.

**Comment by nxPublic** [comment]
Yeah you are probably right. Just changing it is a improvement to giving a option to turn it off doesn't make that much sense.

**Comment by ahnguyen09** [comment]
Will resubmit without project changes just code change to skill.cs

**Pull request closed without merging**
