### PR TITLE
Added Stamina Numerical UI

### PR DESCRIPTION
**Pull request by SSimcox**
This is a small QoL change to the hud that shows stamina as a "current/whole" fraction underneath the stamina bar.

### CODE REVIEW

**Comment by nxPublic** [comment]
This is really awesome ill make sure to merge it after 0.9.2

**Comment by radmint** [comment]
@SSimcox just a small merge conflict to resolve and then it'll be good to go! Thank you!

**Comment by SSimcox** [comment]
Had to fix an issue with changing screen size but should be fixed now.

**Review by nxPublic — APPROVED** [review]

**Comment by nxPublic** [comment]
Awesome!
Merged ❤️

**Pull request merged**
