### PR TITLE
Plants under roof and in all biomes

### PR DESCRIPTION
**Pull request by Algorithman**
As requested by my buddies and in discord:

Plants can be grown under roof and in the wrong biome.
Separate config values (growWithoutSun and noWrongBiome)

Tested against VM dedicated vhserver

### CODE REVIEW

**Comment by SSimcox** [comment]
Addresses #108

**Comment by radmint** [comment]
@Algorithman can you please add the related configuration properties to the .cfg file for all of your PRs?

**Comment by Algorithman** [comment]
I'd rather want to wait for the config recode to be merged and add them there.

**Comment by Algorithman** [comment]
Integrated into #151

**Pull request closed without merging**
