### PR TITLE
Compression with automatic bandwidth management with framework for ZNetScene handoff by server.

### PR DESCRIPTION
**Pull request by slindeneau**
1) Implements on the fly lz4 compression.
-- Compatible without unmodified clients.
2) Automatic bandwidth management on the client end.
-- "Smart" throughput detection and priority message assignment.
-- "Smart" buffering estimation
-- Incorporates compression estimations in buffering computations.
3) Framework for server to do ZNetScene handoff if a client is Throughput limited and choking. 
4) Enables local configuration maintenance for parameters that should not be considered from the server.

### CODE REVIEW

**Comment by nxPublic** [comment]
Impressive work!

**Review by GraveofBears — APPROVED** [review]
looks good

**Review by sbtoonz — COMMENTED** [review]
I pulled down these changes and merged in with current branch testing in a local env the changes seem to be working. This would def be worth some more testing 

// Seems to fail handing the steam ID for client though when using these commits Will investigate

**Comment by slindeneau** [comment]
Hey all, sorry for the delay on working on this. I can probably put the time in to make the serverside vs client side fixes this weekend.

**Comment by sbtoonz** [comment]
> Hey all, sorry for the delay on working on this. I can probably put the time in to make the serverside vs client side fixes this weekend.

would really love to see how this is executed

**Pull request closed without merging**
