### PR TITLE
Mute audio when application loses focus

### PR DESCRIPTION
**Pull request by baconparticles**
Satisfies Feature Request #205
May want to augment this to be client side only or a ui-setttings toggle instead of a config file option.

### CODE REVIEW

**Comment by healiha** [comment]
Thank you for making this pull request!

As you said, we will be looking into adding this to the game settings UI as in my opinion it does not really have it's place in the V+ config file.

**Comment by baconparticles** [comment]
Sounds good. I am looking into how to do that now, but I am new to .NET and dnSpy so it's taking some time.

**Comment by baconparticles** [comment]
Removed config based solution in favor of settings UI based solution.
Known issues: EventSystem does not push OnApplicationFocus while in the settings dialog itself

**Comment by nxPublic** [comment]
Nice work! ❤️

**Review by nxPublic — APPROVED** [review]

**Pull request merged**
